name: Kenya API CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies and Lint
        run: |
          yarn install
          yarn run lint
        env:
          CI: true
      - name: Build
        run: yarn run build
        env:
          CI: true
